# This file was generated by GoReleaser. DO NOT EDIT.
cask "vibecheck" do
  name "vibecheck"
  desc "Vibecheck — AI-powered Git commit assistant."
  homepage "https://github.com/rshdhere/vibecheck"
  version "1.6.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vibecheck"

  on_macos do
    on_intel do
      url "https://github.com/rshdhere/vibecheck/releases/download/v#{version}/vibecheck_Darwin_x86_64.tar.gz",
        verified: "github.com/rshdhere/vibecheck"
      sha256 "7801f09fbdfad1e1ae89723d2ca96a2127c2aceb295eab613e357fb536d626bd"
    end
    on_arm do
      url "https://github.com/rshdhere/vibecheck/releases/download/v#{version}/vibecheck_Darwin_arm64.tar.gz",
        verified: "github.com/rshdhere/vibecheck"
      sha256 "f9205b11a4b60336f89fbd8982fa52e5f5f7c3cf5bedecc2d34875c6baf75ad9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rshdhere/vibecheck/releases/download/v#{version}/vibecheck_Linux_x86_64.tar.gz",
        verified: "github.com/rshdhere/vibecheck"
      sha256 "271017546c896b5c896ebbb5f9b5d5165a77a4da455bdb88e2eb2e63c981c661"
    end
    on_arm do
      url "https://github.com/rshdhere/vibecheck/releases/download/v#{version}/vibecheck_Linux_arm64.tar.gz",
        verified: "github.com/rshdhere/vibecheck"
      sha256 "b49b2aa10b4ce6793248fee12e5f081268d69928fe52c0ef311e97083f60d8f9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vibecheck"]
    end
  end

  # No zap stanza required
end
