# This file was generated by GoReleaser. DO NOT EDIT.
cask "vibecheck" do
  name "vibecheck"
  desc "🌊 Vibecheck — AI-powered Git commit assistant."
  homepage "https://github.com/rshdhere/vibecheck"
  version "1.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vibecheck"

  on_macos do
    on_intel do
      url "https://github.com/rshdhere/vibecheck/releases/download/v#{version}/vibecheck_Darwin_x86_64.tar.gz",
        verified: "github.com/rshdhere/vibecheck"
      sha256 "5546365f612ebd0f1d9894587975f6a1a17b318fe68acec0859c25af4ee7b423"
    end
    on_arm do
      url "https://github.com/rshdhere/vibecheck/releases/download/v#{version}/vibecheck_Darwin_arm64.tar.gz",
        verified: "github.com/rshdhere/vibecheck"
      sha256 "f3ff544d1e72f4920ac8a9b67cca6d3fce6151a7376cc7a7723dee2dc6aac376"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rshdhere/vibecheck/releases/download/v#{version}/vibecheck_Linux_x86_64.tar.gz",
        verified: "github.com/rshdhere/vibecheck"
      sha256 "7635c97f5ae06710b2478e20f582706078a20485cdf759cee0d3182769acdc96"
    end
    on_arm do
      url "https://github.com/rshdhere/vibecheck/releases/download/v#{version}/vibecheck_Linux_arm64.tar.gz",
        verified: "github.com/rshdhere/vibecheck"
      sha256 "f762324556f9c27b5989c71171c6ddfe4fa7e87e3a81d715e258f0fdeb2c82fe"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vibecheck"]
    end
  end

  # No zap stanza required
end
