# This file was generated by GoReleaser. DO NOT EDIT.
cask "vibecheck" do
  name "vibecheck"
  desc "🌊 Vibecheck — AI-powered Git commit assistant."
  homepage "https://github.com/rshdhere/vibecheck"
  version "1.5.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vibecheck"

  on_macos do
    on_intel do
      url "https://github.com/rshdhere/vibecheck/releases/download/v#{version}/vibecheck_Darwin_x86_64.tar.gz",
        verified: "github.com/rshdhere/vibecheck"
      sha256 "adcf620d9ff25ed4e6b8bb46e047f20f9eb60cc0001536db6b3686120e80b370"
    end
    on_arm do
      url "https://github.com/rshdhere/vibecheck/releases/download/v#{version}/vibecheck_Darwin_arm64.tar.gz",
        verified: "github.com/rshdhere/vibecheck"
      sha256 "fa8cf5421980fd420790396e2fc1494bbb8634e6794ad4408237c3d0e478e861"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rshdhere/vibecheck/releases/download/v#{version}/vibecheck_Linux_x86_64.tar.gz",
        verified: "github.com/rshdhere/vibecheck"
      sha256 "87d6b44f5d6a9a42a7ee33025d06cb22cbebf0d7d1b3a31ecf94e17fc695d428"
    end
    on_arm do
      url "https://github.com/rshdhere/vibecheck/releases/download/v#{version}/vibecheck_Linux_arm64.tar.gz",
        verified: "github.com/rshdhere/vibecheck"
      sha256 "e859a09ff01a61d71fad8d99b864400e02990b73b196ae10da10861068f6f205"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vibecheck"]
    end
  end

  # No zap stanza required
end
